
version: "3.9"

services:

  db:
    image: postgres:14.4
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  cache:
    image: redis:7.0.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass aVERYsimplePASS
    volumes:
      - cache:/data/redis

  tworedbirds-core:
    container_name: tworedbirds-core
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - "6600:6600"
    env_file:
      - ./extras/user/dev.env
    depends_on:
      - db
      - cache

volumes:
  cache:
    driver: local