volumes:
  data:

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  tworedbirds:
    container_name: tworedbirds-core
    build:
      context: ./
    ports:
      - "6600:6600"
    volumes:
      - ${PWD}/./:/app:z
    env_file:
      - ./extra/user/${USER}.env
